name: Publish Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: 运行合并脚本
        run: |
          python merge_code.py
          cp output.md /tmp/output.md

      - name: 发布到output分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 设置Git用户信息
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # 创建并切换到一个全新的output分支
          git checkout --orphan output

          # 清理工作区，但保持安全
          git reset --hard
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

          # 恢复markdown文件
          cp /tmp/output.md output.md

          # 提交更改
          git add output.md
          git commit -m "feat: 更新算法模板文档 from ${{ github.sha }}"
          git push origin output -f